twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

    paths:
        '%kernel.project_dir%/templates': app

    globals:
        app_name: '%app_name%'

    date:
        format: d/m/Y Ã  H:i
