vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'username'}

            #inject_on_load: false
            #delete_on_update: true
            #delete_on_remove: true

        mot_image:
            uri_prefix: /images/mot
            upload_destination: '%kernel.project_dir%/public/images/mot'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
