swiftmailer:
  #url: '%env(MAILER_URL)%'
  transport: "smtp"
  host:      "smtp.strato.de"
  #username:  "mimo.berlino@gmail.com"
  #password:  "15$Hannah$16"
  username:  "app@alamouriska.com"
  password:  "emailAlamouriska15"
  #auth_mode: "login"
  port:      "587"
  encryption: "tls"
    #stream_options:
    #ssl:
    #allow_self_signed: true
    #verify_peer: false
  #verify_peer_name: false
  spool:
    type: 'memory'
    #path: '%kernel.project_dir%/var/spool/'